# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0002_auto_20171120_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='belt_exam.User'),
        ),
    ]
